spring:
  application:
    name: aws-xray-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop #表示 hibernate 會用 Entity 來自動產生出對應的資料表格
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: info
    org.apache.coyote.http11.Http11InputBuffer: debug
